// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleNetApplication.Storage;

#nullable disable

namespace SimpleNetApplication.Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SimpleNetApplication.Storage.Models.SimpleDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SimpleModels");
                });

            modelBuilder.Entity("SimpleNetApplication.Storage.Models.SimpleSubDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DbModelFk")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SimpleDbModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimpleDbModelId");

                    b.ToTable("SimpleSubDbModel");
                });

            modelBuilder.Entity("SimpleNetApplication.Storage.Models.SimpleSubDbModel", b =>
                {
                    b.HasOne("SimpleNetApplication.Storage.Models.SimpleDbModel", null)
                        .WithMany("SubModels")
                        .HasForeignKey("SimpleDbModelId");
                });

            modelBuilder.Entity("SimpleNetApplication.Storage.Models.SimpleDbModel", b =>
                {
                    b.Navigation("SubModels");
                });
#pragma warning restore 612, 618
        }
    }
}
